name: hive
description: Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
version: 3.0.0
homepage: https://github.com/hivedb/hive/tree/master/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  crypto: ^3.0.6

dev_dependencies:
  test: ^1.26.3
  mocktail: ^1.0.4
  lints: ^6.0.0
  path: ^1.9.1
  pointycastle: 4.0.0
  build_runner: any
